-- Create orders table
create table public.orders (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default now() not null,
  customer_name text not null,
  customer_email text not null,
  customer_address text not null,
  total_amount numeric not null,
  status text default 'pending' not null
);

-- Create order_items table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade not null,
  product_title text not null,
  quantity integer not null,
  size text not null,
  price numeric not null
);

-- Enable RLS
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Create Policies (Allow Public Insert for Guest Checkout)
create policy "Allow public insert on orders"
on public.orders for insert
to public
with check (true);

create policy "Allow public insert on order_items"
on public.order_items for insert
to public
with check (true);

-- Also allow reading the order just created (useful if we redirect to a success page with the order details)
-- Ideally we would scope this, but for guest checkout with no auth, 'true' is risky for select *
-- safer to only allow insert, or maybe allow select if id matches (but anyone can guess uuid? unlikely but possible).
-- Sticking to prompt request: "policy allowing INSERT for everyone".
