-- 1. Create Table: products
create table products (
  id bigint primary key generated by default as identity,
  created_at timestamptz default now(),
  title text not null,
  price numeric not null, -- Stores price like 45.00
  category text not null, -- Expected values: 'upper', 'pants', 'shoes'
  image_url text not null,
  is_new boolean default false,
  description text
);

-- 2. Security: Enable Row Level Security (RLS)
alter table products enable row level security;

-- Create Policy for Public Read Access
-- Allows anyone (anon and authenticated) to SELECT rows
create policy "Public Read Access"
on products for select
using ( true );

-- 3. Seed Data: Insert 3 Dummy Products
insert into products (title, price, category, image_url, is_new)
values
  ('Vintage Nascar Tee', 45.00, 'upper', '/cat-upper.jpg', true),
  ('Double Knee Work Pants', 80.00, 'pants', '/cat-pants.jpg', false),
  ('Retro Runner Sneakers', 120.00, 'shoes', '/cat-sneakers.jpg', true);
