import type { Metadata } from "next";
import "./globals.css";
import CartDrawer from "./components/CartDrawer"; // Import Drawer

// Note: Removed Geist fonts due to build/network errors.
// import { Geist, Geist_Mono } from "next/font/google";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

/*
import { Gravitas_One } from "next/font/google";
const gravitas = Gravitas_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gravitas",
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CartDrawer /> {/* Global Cart Drawer */}
        {children}
      </body>
    </html>
  );
}
